
# === Этап1: сборка и подготовка зависимостей(Build stage) ===
FROM python:3.10-slim AS builder

WORKDIR /build

# установление зависимостей в отдельную папку (wheel)
RUN pip install --no-cache-dir wheel && \
    pip install --no-cache-dir --user flask


# === Этап2: Минимальный финальный образ (Runtime stage) =====

FROM 
WORKDIR
COPY
COPY
ENV PATH=/

EXPOSE 5000

CMD []
